
// lib/api.ts
import fs from "fs";
import matter from "gray-matter";
import { join } from "path";
import { unified } from "unified";
import remarkGfm from "remark-gfm";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import rehypePrettyCode from "rehype-pretty-code";
import { visit } from "unist-util-visit";
import remarkFigureCaption from "remark-figure-caption";

// memoize/cache the creation of the markdown parser, this sped up the
// building of the blog from ~60s->~10s
let p: ReturnType<typeof getParserPre> | undefined;

function addClasses() {
  return (tree: any) => {
    visit(tree, "element", (node: any) => {
      // We only want to modify figures
      if (node.tagName === "figure") {
        // Handle code blocks generated by rehype-pretty-code
        if (node.properties?.["data-rehype-pretty-code-figure"]) {
          node.properties.className = (node.properties.className || []).concat(
            "not-prose" // Exclude from prose styling
          );
        }
        // Handle image figures
        else {
          const hasImg = node.children.some(
            (child: any) => child.type === "element" && child.tagName === "img"
          );
          if (hasImg) {
            node.properties.className = (
              node.properties.className || []
            ).concat([
              "mx-auto", // Center the figure block itself
              "flex",
              "flex-col",
              "items-center", // Center the figure's children (img, figcaption)
            ]);
            const figcaption = node.children.find(
              (child: any) =>
                child.type === "element" && child.tagName === "figcaption"
            );

            if (figcaption) {
              figcaption.properties = figcaption.properties || {};
              const classes = Array.isArray(figcaption.properties.className)
                ? figcaption.properties.className
                : [];
              if (!classes.includes("text-center")) {
                classes.push("text-center"); // Center the caption text
              }
              figcaption.properties.className = classes;
            }
          }
        }
      }
    });
  };
}

async function getParserPre() {
  return unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkFigureCaption)
    .use(remarkRehype, {
      handlers: {
        figure: (state: any, node: any) => {
          const figureElement = state.h('figure', state.all(node));
          if (node.caption) {
            figureElement.children.push(
              state.h('figcaption', state.all(node.caption)),
            );
          }
          return figureElement;
        },
      },
    })
    // @ts-ignore
    .use(rehypePrettyCode, {
      theme: "one-dark-pro",
      keepBackground: false,
    })
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings, {
      content: (arg) => ({
        type: "element",
        tagName: "a",
        properties: {
          href: "#" + arg.properties?.id,
          style: "margin-right: 10px",
        },
        children: [],
      }),
    })
    .use(addClasses)
    // @ts-ignore
    .use(rehypeStringify);
}

function getParser() {
  if (!p) {
    p = getParserPre().catch((e) => {
      p = undefined;
      throw e;
    });
  }
  return p;
}

export async function getPostById(id: string) {
  const realId = id.replace(/\.md$/, "");
  const fullPath = join("src/_posts", `${realId}.md`);
  const { data, content } = matter(
    await fs.promises.readFile(fullPath, "utf8")
  );

  const parser = await getParser();
  const html = await parser.process(content);

  // Convert date to string if it's a Date object
  const dateStr = data.date instanceof Date 
    ? data.date.toISOString().slice(0, 10)
    : data.date;

  return {
    ...data,
    title: data.title,
    id: realId,
    date: dateStr,
    coverImage: data.coverImage || null,
    html: html.value.toString(),
  };
}

export async function getAllPosts() {
  const posts = await Promise.all(
    fs.readdirSync("src/_posts").map((id) => getPostById(id))
  );
  return posts.sort((post1, post2) => (post1.date > post2.date ? -1 : 1));
}
