
// lib/api.ts
import fs from "fs";
import matter from "gray-matter";
import { join } from "path";
import { unified } from "unified";
import remarkGfm from "remark-gfm";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeRaw from "rehype-raw";
import rehypeStringify from "rehype-stringify";
import rehypePrettyCode from "rehype-pretty-code";
import { visit } from "unist-util-visit";
import remarkFigureCaption from "remark-figure-caption";

// memoize/cache the creation of the markdown parser, this sped up the
// building of the blog from ~60s->~10s
let p: ReturnType<typeof getParserPre> | undefined;
const postSvgMapCache = new Map<string, Promise<PostSvgMap | null>>();

interface PostSvgMapImageEntry {
  src: string;
  svgSrc?: string;
  status?: string;
  layers?: PostSvgMapLayerEntry[];
}

interface PostSvgMapLayerEntry {
  kind?: string;
  src: string;
  opacity?: number;
  blend?: string;
}

interface PostSvgMap {
  version: number;
  postId: string;
  images: PostSvgMapImageEntry[];
}

function appendClassNames(node: any, classNames: string[]) {
  node.properties = node.properties || {};
  const existing = Array.isArray(node.properties.className)
    ? node.properties.className
    : node.properties.className
      ? [node.properties.className]
      : [];

  for (const className of classNames) {
    if (!existing.includes(className)) {
      existing.push(className);
    }
  }

  node.properties.className = existing;
}

function addClasses() {
  return (tree: any, file: any) => {
    const svgMapBySrc: Map<string, PostSvgMapImageEntry> =
      file?.data?.svgMapBySrc instanceof Map ? file.data.svgMapBySrc : new Map();

    visit(tree, "element", (node: any, index: number | undefined, parent: any) => {
      if (node.tagName === "img") {
        const src = typeof node.properties?.src === "string" ? node.properties.src : "";
        const mapped = svgMapBySrc.get(src);
        if (!mapped) {
          return;
        }

        const layers = Array.isArray(mapped.layers) ? mapped.layers : [];

        if (layers.length > 1 && parent && typeof index === "number") {
          const originalAlt = typeof node.properties?.alt === "string" ? node.properties.alt : "";

          const layerChildren = layers.map((layer, layerIndex) => {
            const isTop = layerIndex === layers.length - 1;
            const classes = ["svg-layer", `svg-layer-${layer.kind || `layer-${layerIndex}`}`];
            if (isTop) {
              classes.push("svg-layer-fg");
            }

            const properties: Record<string, any> = {
              src: layer.src,
              alt: isTop ? originalAlt : "",
              className: classes,
              loading: "lazy",
              decoding: "async",
            };
            if (!isTop) {
              properties["aria-hidden"] = "true";
            } else {
              properties.className.push("svg-3d-source");
            }

            return {
              type: "element",
              tagName: "img",
              properties,
              children: [],
            };
          });

          parent.children[index] = {
            type: "element",
            tagName: "span",
            properties: {
              className: ["svg-depth-card", "svg-depth-card--generated"],
            },
            children: layerChildren,
          };
          return;
        }

        if (mapped.svgSrc) {
          node.properties = node.properties || {};
          node.properties.src = mapped.svgSrc;
          appendClassNames(node, ["svg-3d-source"]);
        }
        return;
      }

      // We only want to modify figures
      if (node.tagName === "figure") {
        // Handle code blocks generated by rehype-pretty-code
        if (node.properties?.["data-rehype-pretty-code-figure"]) {
          appendClassNames(node, ["not-prose"]);
        }
        // Handle image figures
        else {
          const imageChildren = node.children.filter(
            (child: any) => child.type === "element" && child.tagName === "img"
          );
          const hasImg = imageChildren.length > 0;

          if (hasImg) {
            appendClassNames(node, [
              "mx-auto", // Center the figure block itself
              "flex",
              "flex-col",
              "items-center", // Center the figure's children (img, figcaption)
            ]);

            const figcaption = node.children.find(
              (child: any) =>
                child.type === "element" && child.tagName === "figcaption"
            );

            if (figcaption) {
              figcaption.properties = figcaption.properties || {};
              const classes = Array.isArray(figcaption.properties.className)
                ? figcaption.properties.className
                : [];
              if (!classes.includes("text-center")) {
                classes.push("text-center"); // Center the caption text
              }
              figcaption.properties.className = classes;
            }
          }
        }
      }
    });
  };
}

async function getParserPre() {
  return unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkFigureCaption)
    .use(remarkRehype, {
      allowDangerousHtml: true,
      handlers: {
        figure: (state: any, node: any) => {
          const figureElement = state.h('figure', state.all(node));
          if (node.caption) {
            figureElement.children.push(
              state.h('figcaption', state.all(node.caption)),
            );
          }
          return figureElement;
        },
      },
    })
    .use(rehypeRaw)
    // @ts-ignore
    .use(rehypePrettyCode, {
      theme: "one-dark-pro",
      keepBackground: false,
    })
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings, {
      content: (arg) => ({
        type: "element",
        tagName: "a",
        properties: {
          href: "#" + arg.properties?.id,
          style: "margin-right: 10px",
        },
        children: [],
      }),
    })
    .use(addClasses)
    // @ts-ignore
    .use(rehypeStringify);
}

async function loadPostSvgMap(postId: string): Promise<PostSvgMap | null> {
  const mapPath = join("src/_posts", `${postId}.svg-map.json`);

  let raw: string;
  try {
    raw = await fs.promises.readFile(mapPath, "utf8");
  } catch (err: any) {
    if (err?.code === "ENOENT") {
      return null;
    }
    throw err;
  }

  const parsed = JSON.parse(raw) as Partial<PostSvgMap>;
  if (!Array.isArray(parsed.images)) {
    return null;
  }

  return {
    version: Number(parsed.version || 1),
    postId: String(parsed.postId || postId),
    images: parsed.images,
  };
}

function getPostSvgMap(postId: string) {
  const cached = postSvgMapCache.get(postId);
  if (cached) {
    return cached;
  }

  const pending = loadPostSvgMap(postId).catch((err) => {
    postSvgMapCache.delete(postId);
    console.warn(`[blog-svg-map] Failed to load ${postId}.svg-map.json: ${String(err?.message || err)}`);
    return null;
  });

  postSvgMapCache.set(postId, pending);
  return pending;
}

function getParser() {
  if (!p) {
    p = getParserPre().catch((e) => {
      p = undefined;
      throw e;
    });
  }
  return p;
}

export async function getPostById(id: string) {
  const realId = id.replace(/\.md$/, "");
  const fullPath = join("src/_posts", `${realId}.md`);
  const { data, content } = matter(
    await fs.promises.readFile(fullPath, "utf8")
  );

  const parser = await getParser();
  const svgMap = await getPostSvgMap(realId);
  const svgMapBySrc = new Map<string, PostSvgMapImageEntry>(
    (svgMap?.images || [])
      .filter((entry) => {
        if (!entry || typeof entry.src !== "string") {
          return false;
        }
        if (entry.status && entry.status !== "ok") {
          return false;
        }
        const hasValidSvg =
          typeof entry.svgSrc === "string" &&
          entry.svgSrc.length > 0 &&
          fs.existsSync(join("public", entry.svgSrc.replace(/^\//, "")));

        const validLayers = Array.isArray(entry.layers)
          ? entry.layers.filter(
              (layer) =>
                layer &&
                typeof layer.src === "string" &&
                layer.src.length > 0 &&
                fs.existsSync(join("public", layer.src.replace(/^\//, "")))
            )
          : [];

        if (!hasValidSvg && !validLayers.length) {
          return false;
        }

        entry.layers = validLayers;
        return true;
      })
      .map((entry) => [entry.src, entry])
  );

  const html = await parser.process({
    value: content,
    data: {
      svgMapBySrc,
    },
  });

  return {
    ...data,
    title: data.title,
    id: realId,
    date: `${data.date?.toISOString().slice(0, 10)}`,
    coverImage: data.coverImage || null,
    html: html.value.toString(),
  };
}

export async function getAllPosts() {
  const posts = await Promise.all(
    fs
      .readdirSync("src/_posts")
      .filter((id) => id.endsWith(".md"))
      .map((id) => getPostById(id))
  );
  return posts.sort((post1, post2) => (post1.date > post2.date ? -1 : 1));
}
